###
POST http://localhost:3000/api/login/
X-API-Key: RHS
Accept: application/json
Content-Type: application/json

{
   "user_name": "Alima",
   "user_pass": "ALiudi"
}

###
DELETE http://localhost:3000/api/deleteuser
X-API-Key: RHS
Accept: application/json
Content-Type: application/json

{
   "user_name": "Ali"
}

###
GET http://localhost:3000/api/logout
X-API-Key: RHS

###
POST http://localhost:3000/api/regis/
Accept: application/json
Content-Type: application/json
X-API-Key: RHS

{
   "user_name": "Ali",
   "user_pass": "ALiudin",
   "role_id" : 2
}

###
PUT http://localhost:3000/api/changepass
X-API-Key: RHS
Accept: application/json
Content-Type: application/json

{
   "user_pass": "ALiudi"
}

GET http://localhost:3000/api/GetByRole/1
X-API-Key: RHS