###
POST http://localhost:3000/api/login/
X-API-Key: RHS
Accept: application/json
Content-Type: application/json

{
   "user_name": "Ali",
   "user_pass": "ALiudin"
}

###
GET http://localhost:3000/api/GetByRole/1
X-API-Key: RHS

###
GET http://localhost:3000/api/logout
X-API-Key: RHS

###
POST http://localhost:3000/api/regis/
Accept: application/json
Content-Type: application/json
X-API-Key: RAHASIA

{
   "user_name": "",
   "user_pass": "ALiudin",
   "role_id" : 1
}